"""Create a deterministic labeled PDF for metric plumbing; not a real-world benchmark."""
import json
import pathlib
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import Table, TableStyle

ROOT=pathlib.Path(__file__).resolve().parents[1]
dest=ROOT/'data/labeled';dest.mkdir(parents=True,exist_ok=True)
pdf=dest/'synthetic-complex-tables.pdf';gt=dest/'synthetic-complex-tables.gt.json'
width,height=A4

def cell(row,col,text,rowspan=1,colspan=1,header=False,top=90,x=55,widths=(100,100,100,100),heights=(30,30,30,30)):
    return {'row':row,'col':col,'rowspan':rowspan,'colspan':colspan,'text':text,'header':header,
            'bbox':[x+sum(widths[:col]),top+sum(heights[:row]),x+sum(widths[:col+colspan]),top+sum(heights[:row+rowspan])],
            'source':{'kind':'deterministic_reportlab_fixture'}}

canvas=Canvas(str(pdf),pagesize=A4,pageCompression=0)
tables=[]
data=[['Region','Fiscal year 2025','',''],['','Q1','Q2','Q3'],['East','12','14','18'],['Notes: provisional','','','']]
spans=[('SPAN',(0,0),(0,1)),('SPAN',(1,0),(3,0)),('SPAN',(0,3),(3,3))]
style=[('GRID',(0,0),(-1,-1),1,colors.black),('BACKGROUND',(0,0),(-1,1),colors.lightgrey),('VALIGN',(0,0),(-1,-1),'MIDDLE')]+spans
t=Table(data,colWidths=[100]*4,rowHeights=[30]*4);t.setStyle(TableStyle(style));tw,th=t.wrapOn(canvas,width,height)
t.drawOn(canvas,55,height-90-th);canvas.drawString(55,height-55,'Labeled merged-header regression fixture')
cells=[cell(0,0,'Region',2,1,True),cell(0,1,'Fiscal year 2025',1,3,True),
       cell(1,1,'Q1',header=True),cell(1,2,'Q2',header=True),cell(1,3,'Q3',header=True),
       cell(2,0,'East'),cell(2,1,'12'),cell(2,2,'14'),cell(2,3,'18'),cell(3,0,'Notes: provisional',1,4)]
html='<table><thead><tr><th rowspan="2">Region</th><th colspan="3">Fiscal year 2025</th></tr><tr><th>Q1</th><th>Q2</th><th>Q3</th></tr></thead><tbody><tr><td>East</td><td>12</td><td>14</td><td>18</td></tr><tr><td colspan="4">Notes: provisional</td></tr></tbody></table>'
tables.append({'id':'fixture-p1','page':1,'bbox':[55,90,55+tw,90+th],'html':html,'cells':cells})
canvas.showPage()
data2=[['Department','Jan','Feb','Mar'],['Research','31','29','35'],['Operations','18','21','19'],['Total','49','50','54']]
t=Table(data2,colWidths=[100]*4,rowHeights=[30]*4)
t.setStyle(TableStyle([('LINEBELOW',(0,0),(-1,0),.5,colors.grey),('VALIGN',(0,0),(-1,-1),'MIDDLE')]))
tw,th=t.wrapOn(canvas,width,height);t.drawOn(canvas,55,height-90-th);canvas.drawString(55,height-55,'Labeled borderless regression fixture')
cells2=[cell(r,c,value,header=r==0) for r,row in enumerate(data2) for c,value in enumerate(row)]
html2='<table><thead><tr><th>Department</th><th>Jan</th><th>Feb</th><th>Mar</th></tr></thead><tbody><tr><td>Research</td><td>31</td><td>29</td><td>35</td></tr><tr><td>Operations</td><td>18</td><td>21</td><td>19</td></tr><tr><td>Total</td><td>49</td><td>50</td><td>54</td></tr></tbody></table>'
tables.append({'id':'fixture-p2','page':2,'bbox':[55,90,55+tw,90+th],'html':html2,'cells':cells2})
canvas.save()
gt.write_text(json.dumps({'provenance':'deterministically generated by scripts/make_fixture.py','tables':tables},indent=2))
print(pdf);print(gt)
